### ISSUE TITLE
RPI3 crashes on internet exception when running in crontab

### ISSUE THREAD

**Issue by Gabrielkyne** [tech4nature/HogPi#29]
The exceptions do not prevent the system crashing when no internet.

Result:
Crashes 

cron log shows
Traceback (most recent call last):
  File "/home/pi/HogPi/app/hedge.py", line 235, in <module>
    result = main(last_ran)
  File "/home/pi/HogPi/app/hedge.py", line 171, in main
    post(box_id, rfid_tag, to_post)  # Posts data
  File "/home/pi/HogPi/app/hedge.py", line 110, in post
    time = datetime.strptime(strtime, "%Y-%m-%d-%H-%M-%S-%z")
  File "/usr/lib/python3.5/_strptime.py", line 510, in _strptime_datetime
    tt, fraction = _strptime(data_string, format)
  File "/usr/lib/python3.5/_strptime.py", line 343, in _strptime
    (data_string, format))
ValueError: time data '2019-07-21-02-43-31' does not match format '%Y-%m-%d-%H-%M-%S-%z'

Trial : 
Change to crontab same type of call as remoteCam
Result: FAIL as above

**Comment by Gabrielkyne** [comment]
Yes problem was with posts from pizero which did not have -%z.  Thanks Jack could not see the wood from the trees on that one!
 commit -195
